apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-symbolic-configmap
data:
  myvalue: "Hello World"
  drink: {{ .Values.favorite.drink }}
  food: {{ .Values.favorite.food }}
  salad: {{ .Values.global.salad }}

